![imagen](./img/ejercicios.png)

In [1]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [25]:
my_array = np.arange(10)
print(my_array)
print(my_array[-1::-2])  # First element
print(my_array[my_array%2 == 1][::-1])  # Last element

[0 1 2 3 4 5 6 7 8 9]
[9 7 5 3 1]
[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [35]:
my_array[-2:-4:-1]

array([8, 7])

## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [59]:
# AQUÍ VA VUESTRO CÓDIGO

my_array[2::-1]  # First element

array([2, 1, 0])

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [64]:
secuencia = np.arange(1,21,1)
print(secuencia)

matrix = secuencia.reshape(4,5)
print(matrix)

matrix_invertida = matrix.reshape(5,4)
print(matrix_invertida)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [ ]:
matrix[0:2, 0:2]  

array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [89]:
matrix[0::2, 0::2] 

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [87]:
matrix[0:3,-1::-1] # First element

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [114]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

x_filtrado = x[x == "Loro"]
print(x_filtrado)

x_filtrado = x[np.where(x == "Loro")]
print(x_filtrado) 

x_filtrado = x[np.isin(x, ["Loro"])]
print(x_filtrado)

x_filtrado = np.array([i for i in x  if i == "Loro"])
print(x_filtrado)


['Loro' 'Loro']
['Loro' 'Loro']
['Loro' 'Loro']
['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [118]:
secuencia = np.arange(1,21)
print(secuencia)

matrix = secuencia.reshape(2,5,2)
print(matrix)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]
  [15 16]
  [17 18]
  [19 20]]]


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [119]:
# AQUÍ VA VUESTRO CÓDIGO
my_array = np.zeros(10, dtype = int)

print(f"El array ocupa {my_array.nbytes} bytes en memoria.")

my_array[3] = 1

print("El array modificado es:", my_array)



El array ocupa 80 bytes en memoria.
El array modificado es: [0 0 0 1 0 0 0 0 0 0]


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [131]:
my_vector = np.arange(10,50)
print(my_vector)

vector_invertido = my_vector[-1::-1]
print(vector_invertido)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [ ]:
x = np.array([1,2,0,0,4,0])


output = np.nonzero(x!=0)[0]

print(output)



[0 1 4]


## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [171]:
# AQUÍ VA VUESTRO CÓDIGO

matrix1010 = np.random.randint(1, 25, (10, 10))
print(matrix1010)

minimo = matrix1010.min()
print(minimo)

maximo = matrix1010.max()
print(maximo)



[[ 3  8 18 19 12 18 15 15 11  3]
 [10 15 12  3 20 22  5  6 22  3]
 [22 14 21  2 20 13  6 19 24  5]
 [ 4  7 15  4 10  4 21 11 15 18]
 [10 23  8  3 10 12  5 13 23 19]
 [22 12  4  3  7 10 20 22 19  9]
 [ 1  2 13  8 23 16 21 20  9  9]
 [24  2  3 12 14 11 24 20 13  8]
 [ 7  6 11 18  7  2  6 13  9  2]
 [11  9 16 14  8  7 20 10 15 22]]
1
24


## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [179]:
# AQUÍ VA VUESTRO CÓDIGO

vector = np.random.randint(1, 100, 30)
print(vector)

media = vector.mean()
print("----------------------------------")

print(f"La media del vector es: {round(media,4)}")

[ 8 25 47 95 70 87 30 72 92 79 95 22 26 67 61 94 42 97 65 65 28 41 41 13
 26 11 14 97 67 27]
----------------------------------
La media del vector es: 53.4667


## Ejercicio 15
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [190]:
# Matriz de ceros
matriz = np.zeros((10, 10), dtype=int)
# Borde con unos
matriz[0, :] = 1
matriz[-1, :] = 1
matriz[:, 0] = 1
matriz[:, -1] = 1

print(matriz)

print("-------------------------------------------------")

print(f"La dimensi&oacute;n de la matriz es: {matriz.ndim}")  


[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]
-------------------------------------------------
La dimensi&oacute;n de la matriz es: 2


## Ejercicio 16
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [ ]:
 # Matriz de ceros
matriz = np.zeros((8,8), dtype=int)

matriz[1::2, ::2] = 1
matriz[::2, 1::2] = 1
print(matriz)

print("----------------")
# Otra forma de hacerlo
# Matriz de 1s
matriz = np.ones((8, 8), dtype=int)

for i in range(0,8,1):
  print(i)
  if i%2==0:
    matriz[i,::2]=0
  else:
    matriz[i,1::2]=0
              
print(matriz)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
----------------
----------------
0
1
2
3
4
5
6
7
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 17
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [ ]:
a = np.array([0,1]) 
b = np.array([1,0])

print(np.tile(np.array([np.tile(a,4), np.tile(b,4)]), (4,1)))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [309]:
matriz = np.random.randint(1, 10, (5, 5))

print(matriz)
print("-------------------------------------------------")

print(matriz.mean())
print(matriz.std())

matriz[::,::]=(matriz[::,::]-matriz.mean())/matriz.std()

print(matriz)




[[9 1 3 9 1]
 [6 6 1 3 9]
 [8 6 5 2 4]
 [2 7 4 9 7]
 [9 8 6 1 2]]
-------------------------------------------------
5.12
2.9026884090442775
[[ 1 -1  0  1 -1]
 [ 0  0 -1  0  1]
 [ 0  0  0 -1  0]
 [-1  0  0  1  0]
 [ 1  0  0 -1 -1]]


## Ejercicio 19
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [315]:
secuencia = np.arange(11)
print(f"secuencia original: {secuencia}")

# nuevo array para sustituir por -1 los elementos entre 3 y 8.
secuencia_modificada = np.where((secuencia > 3) & (secuencia < 8), -1, secuencia)
print("secuencia modificado:", secuencia_modificada)

# nuevo array que niegue los elementos entre 3 y 8.
secuencia_negada = np.where((secuencia > 3) & (secuencia < 8), ~secuencia, secuencia)
print("secuencia negada:", secuencia_negada)


secuencia original: [ 0  1  2  3  4  5  6  7  8  9 10]
secuencia modificado: [ 0  1  2  3 -1 -1 -1 -1  8  9 10]
secuencia negada: [ 0  1  2  3 -5 -6 -7 -8  8  9 10]
